### ISSUE TITLE
Improve the sharing options at the bottom of a single post

### ISSUE THREAD

**Issue by Alecaddd** [thundernest/thunderblog#31]
We should add a lot more sharing options at the bottom of a blog post, things like:
- Mastodon/Fediverse
- Facebook
- Reddit
- Pinterest
- Mail
Something else?

Also, the hover effect should have a CSS transition for the color, from the code it seems it should have it but visually it switches color immediately.

**Comment by KillYourFM** [comment]
Good call. My suggestion: 

- Mail (intentionally first!)
- Twitter
- WhatsApp
- Telegram
- LinkedIn
- Facebook

**Comment by devmount** [comment]
I can implement those additional platforms and make them configurable in Wordpress, as soon as I'm free again to do so (see my comment [here](https://github.com/thundernest/thunderblog/issues/28#issuecomment-1282220107)).

**Comment by devmount** [comment]
I implemented @KillYourFM's suggestions in #32. Do you also want Mastodon, Reddit and Pinterest? I don't know how to provide a sharing link to Mastodon since it's decentralized...

**Comment by KillYourFM** [comment]
> I implemented @KillYourFM's suggestions in #32. Do you also want Mastodon, Reddit and Pinterest? I don't know how to provide a sharing link to Mastodon since it's decentralized...

**Thank you!** 

I don't consider Reddit and Pinterest important for sharing (we have people on Reddit who will share blog content already), but let's leave that decision for @Alecaddd to make. 

As for Mastodon, it seems problematic right now due to its decentralized nature. A button can be generated for Wordpress, but that still requires that people know their instance URL, and still requires them to enter what the text of the post will be. (It seems easier to simply copy the content's URL and tab over to your instance and share it there.)

**Comment by Alecaddd** [comment]
I would add reddit, I think it's handy for a lot of users and the fact that we have a subreddit for Thunderbird makes sense having it.

**Comment by Alecaddd** [comment]
@micahilbery is experimenting with a share to mastodon custom code, he'll take care of adding something like that for the blog.

**Comment by devmount** [comment]
Alright, I also added Reddit and merged the PR ✔️
