### ISSUE TITLE
Create a dedicated page for Newsletter signups

### ISSUE THREAD

**Issue by KillYourFM** [thundernest/thunderblog#34]
The website needs a standalone URL (such as newsletter.thunderbird.net) to act as a landing page for new Newsletter subscribers. Currently, it is just a section integrated into the homepage of thunderbird.net (screenshot attached).

The page design can be simple. Being able to [embed previous newsletter campaigns](https://mailchimp.com/help/add-an-email-campaign-archive-to-your-website/) into this page would be a useful bonus. 

The copy for the page should read:

**See exciting previews of upcoming features, read the latest desktop Thunderbird and mobile Thunderbird news, and enjoy personalized tips to protect your privacy and maximize your productivity! From the Thunderbird team directly to your inbox.**
<img width="629" alt="Screenshot 2022-12-06 at 11 36 28" src="https://user-images.githubusercontent.com/47599547/205888490-863ee824-fcd9-4518-8106-b76f00720aeb.png">

**Comment by MelissaAutumn** [comment]
I believe we might be switching newsletter providers. I'll put this ticket on hold/question until this is resolved, in case additional edits are required.

**Comment by Sancus** [comment]
A few comments here:
1) It's not clear to me if the blog is really the right place for this, is there a reason the issue was filed here?
2) If we want to localize this it's MUCH simpler to add it as part of https://github.com/thundernest/thunderbird-website and use the website's existing l10n system.
3) It's also not clear to me why we need a subdomain for this, as opposed to thunderbird.net/newsletters/ or something. But that's less important.

**Comment by MelissaAutumn** [comment]
This has been resolved over at https://github.com/thundernest/thunderbird-website/issues/371.
